### ISSUE TITLE
Hovercard test suite

### ISSUE THREAD

**Issue by anleac** [anleac/blank_public_repo#1]

**Comment by anleac** [comment]
Referenced issue: https://github.com/anleac/blank_public_repo/issues/3

Refenced issue comment: https://github.com/anleac/blank_public_repo/issues/3#issuecomment-1089940871

referenced pull request: #2 

referenced pull request comment: https://github.com/anleac/blank_public_repo/pull/2#issuecomment-1089942933

Review by author: https://github.com/anleac/blank_public_repo/pull/2#pullrequestreview-933004873

Review comment by author: https://github.com/anleac/blank_public_repo/pull/2/files#r843601518

Commit comment (should not work): https://github.com/anleac/blank_public_repo/commit/8c384719ea1af20b448417d69b5f8193c2871460#commitcomment-70585432

**Comment by alexus37** [comment]
Task list: anleac/blank_public_repo/issues/9

**Comment by alexus37** [comment]
many labels for an issue: anleac/blank_public_repo/issues/10
